### ISSUE TITLE
fetch.py breaks in pypy --- with fix

### ISSUE THREAD

**Issue by bluegrue** [ClimateCodeFoundation/ccc-gistemp#2]
When trying to run fetch.py in pypy 2.5.0 on Windows the data import failed while reading the second tar.gz file. My guess: the fileobj from the first call never gets closed (tarfile.open does not do that for you) and messes up the second call. 

Replacing line 379 in the extract_tar routine
        tar = tarfile.open('', mode='r', fileobj=open(name,'r'))
with
        tar = tarfile.open(name = name, mode='r')
fixes the issue. 

To improve readability you may want to change the parameters of extract_tar from
       def extract_tar(self, name, members):
to
        def extract_tar(self, archivefilename, members):
in which case the fix becomes 
        tar = tarfile.open(name = archivefilename, mode='r')
and the exception handler 
       raise Error("Couldn't find these members in '%s': %s" % (archivefilename, [member[0] for member in members]))

**Comment by drj11** [comment]
Thanks for reporting this by the way!

Ah, yes, the bug is failing to close `fileobj` promptly. Can you paste a typical traceback from your terminal into this issue please?

**Comment by bluegrue** [comment]
Here's the traceback:

```
input/ghcnm.tavg.latest.qca.tar.gz already exists.
  ... input/ghcnm.tavg.qca.dat already exists.
input/GISTEMPv3_sources.tar.gz already exists.
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "tool/fetch.py", line 559, in <module>
    sys.exit(main())
  File "tool/fetch.py", line 551, in main
    fetcher.fetch()
  File "tool/fetch.py", line 127, in fetch
    self.fetch_one(url, local, members=members)
  File "tool/fetch.py", line 301, in fetch_one
    self.fetch_url(url, local, members)
  File "tool/fetch.py", line 340, in fetch_url
    self.extract(name, members)
  File "tool/fetch.py", line 363, in extract
    self.extract_tar(name, members)
  File "tool/fetch.py", line 407, in extract_tar
    raise Error("Couldn't find these members in '%s': %s" % (name, [member[0] for member in members]))
Error: Couldn't find these members in 'input/GISTEMPv3_sources.tar.gz': ['/STEP0/input_files/antarc1.list', '/STEP0/inpu
t_files/antarc1.txt', '/STEP0/input_files/antarc2.list', '/STEP0/input_files/antarc2.txt', '/STEP0/input_files/antarc3.l
ist', '/STEP0/input_files/antarc3.txt', '/STEP0/input_files/t_hohenpeissenberg_200306.txt_as_received_July17_2003', '/ST
EP1/input_files/mcdw.tbl', '/STEP1/input_files/ushcn3.tbl', '/STEP1/input_files/sumofday.tbl', '/STEP1/input_files/v3.in
v', '/STEP0/input_files/Ts.strange.v3.list.IN_full', '/STEP4_5/input_files/oisstv2_mod4.clim.gz']
```

As you can see, the first call for "ghcnm.tavg.qca.dat" works, whereas the second call for "GISTEMPv3_sources.tar.gz" breaks. Was there a specific reason to use the fileobj syntax as opposed to just using the filename, that I am missing?

**Comment by drj11** [comment]
@bluegrue We can't test on Windows, so I'd love it if you gave the latest master a spin. Thanks!

**Comment by bluegrue** [comment]
Got the new master.zip and let it run. fetch.py now works like a charm with pypy-2.5.0-win32 under Windows 8 64-bit. :+1: 

Thanks!
